# Logging configuration
logging:
  version: 1
  formatters:
    ETL:
      format: "ETL - %(name)s - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
#    console:
#      class: logging.StreamHandler
#      formatter: ETL
#      level: DEBUG
    file_handler:
      class: logging.FileHandler
      level: INFO
      formatter: ETL
      filename: Logs/etl.log
      encoding: utf8
      mode: a
  root:
    level: INFO
    handlers: [ file_handler ]